kanatis_app/urls.py
from django.urls import path
from .views import (
    HomePageView, ServicePageView, BlogPageView,
    BlogDetailView, aboutus, teams, detail_team,contactus, SubServicePageView,
    SubServiceDetailView, SubAboutDetailView
)
app_name='kanatis'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('services/', ServicePageView.as_view(), name='services'),
    path('services/<str:service>/', SubServicePageView.as_view(), name='services-type'),
    path('services/<str:service>/<str:subservice>/', SubServiceDetailView.as_view(), name='service-detail'),
    path('news/', BlogPageView.as_view(), name='blog'),
    path('news/<str:slug>', BlogDetailView.as_view(), name='blog_detail'),
    path('about/', aboutus, name='about'),
    path('about/<str:slug>', SubAboutDetailView.as_view(), name='subabout'),
    path('contact/', contactus, name='contact'),
    path('teams/', teams, name='teams'),
    path('teams/<str:slug>/', detail_team, name='detail_team'),
]

kanatis_pro/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  # path('jet/', include('jet.urls', 'jet')),
                  # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
                  path('admin/', admin.site.urls),
                  path('rosetta/', include('rosetta.urls'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('kanatis_app.urls', namespace='kanatis')),

    prefix_default_language=False

)

kanatis_app/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _


def latin_slugify(str):
    str = str.replace(" ", "-")
    str = str.replace("?", "-")
    str = str.replace(",", "-")
    str = str.replace("ə", "e")
    str = str.replace("ö", "o")
    str = str.replace("ç", "ch")
    str = str.replace("ş", "sh")
    str = str.replace("ı", "i")
    str = str.replace("ü", "u")
    str = str.replace("ğ", "gh")
    str = str.replace("İ", "i")
    str = str.replace("Ə", "e")
    str = str.replace("Ö", "o")
    str = str.replace("Ü", "u")
    return str.lower()

ORDER = (
    (1, _("First position")),
    (2, _("Second position")),
    (3, _("Third position")),
    (4, _("Fourth position")),
    (5, _("fifth position")),
    (6, _("sixth position")),
    (7, _("seventh position")),
    (8, _("eight position")),
    (9, _("ninenth position")),
    (10, _("tenth position"))
)

class Post(models.Model):
    title = models.CharField(max_length=100)
    short_content = models.TextField(max_length=300)
    content = RichTextField()
    image = models.ImageField(upload_to='postimages/')
    category = models.ForeignKey('Service', related_name='posts', on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, null=True, editable=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def save(self, *args, **kwargs):
        self.slug = latin_slugify(self.title[:48])
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}'


class Carousel(models.Model):
    content = models.CharField(max_length=100, )
    image = models.ImageField(upload_to='carousels/')
    service = models.ForeignKey('Service', related_name='carousels', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.service.name}'


class Service(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    order = models.PositiveIntegerField(_('Service order'), default=1)
    image = models.ImageField(upload_to='services/')
    slug = models.SlugField(unique=True, null=True, editable=False)

    def __str__(self):
        return f'{ self.name }'

    def save(self, *args, **kwargs):
        self.slug = latin_slugify(self.name[:48])
        super(Service, self).save(*args, **kwargs)
    class Meta:
        ordering = ['order']

class SubService(models.Model):
    title = models.CharField(max_length=30)
    order = models.PositiveIntegerField(_('Subservice order'), default=1)
    image = models.ImageField(upload_to='subservices/')
    content = RichTextField()
    service = models.ForeignKey('Service', related_name='subservice', on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, null=True, editable=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{ self.title }'

    def save(self, *args, **kwargs):
        self.slug = latin_slugify(self.title[:48])
        super(SubService, self).save(*args, **kwargs)

    class Meta:
        ordering = ['order']


class SocialNetwork(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)
    icon = models.CharField(max_length=55)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return f'{self.name}'


class TextPages(models.Model):
    team_member = models.CharField(max_length=255, null=True, blank=True)
    team = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Səhifə yazıları"


class AboutUs(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    img = models.ImageField(upload_to='about/')
    description = RichTextField()

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name_plural = "About"


class SubAboutUs(models.Model):
    title = models.CharField(max_length=255, null=True, blank=True)
    img = models.ImageField(upload_to='subabout/')
    description = RichTextField()
    order = models.PositiveIntegerField(_('Position ordering'), choices=ORDER, default=1)
    about = models.ForeignKey('AboutUs', related_name='subabouts', on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, null=True, editable=False)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = latin_slugify(self.title[:48])
        super(SubAboutUs, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name_plural = "Sub about"
        ordering = ['order']




class Team(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    order = models.PositiveIntegerField(_('Position ordering'), choices=ORDER, default=2)
    short_desc = models.TextField('Short description')
    desc = RichTextField('Description')
    status = models.CharField('Position', max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    number = models.CharField('Phone number', max_length=255, null=True, blank=True)
    img = models.ImageField('profile image', upload_to='teams')
    facebook = models.CharField(max_length=255, null=True, blank=True)
    instagram = models.CharField(max_length=255, null=True, blank=True)
    twitter = models.CharField(max_length=255, null=True, blank=True)
    slug = models.SlugField(unique=True, null=True, editable=False)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name_plural = "Komanda"


    def save(self, *args, **kwargs):
        self.slug = latin_slugify(self.name[:48])
        super(Team, self).save(*args, **kwargs)


class TeamServices(models.Model):
    service = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)
    serv_name = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.serv_name}'

    class Meta:
        verbose_name_plural = "Komanda Servisləri"



class SertificateTeam(models.Model):
    sertificate = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)
    sertificate_name = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name_plural = "Komanda Sertifikatları"
        verbose_name = "Komanda Sertifikatı"

    def __str__(self):
        return self.sertificate_name


class Contact(models.Model):
    address = models.CharField(max_length=255, null=True, blank=True)
    gmap_embed_address = models.TextField('Gmap embeded iframe', max_length=1000)
    social_networks = models.ManyToManyField('SocialNetwork',)
    email = models.EmailField()
    office_hour = models.CharField(max_length=255, null=True, blank=True)
    number = models.CharField('Phone', max_length=20, null=True, blank=True)
    office_phone = models.CharField(max_length=20, null=True, blank=True)
    text = RichTextField()
    
    class Meta:
        verbose_name_plural = "Əlaqə"

    def __str__(self):
        return f'{ self.email } | { self.address }'


class ContactUs(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    desc = models.TextField()

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name_plural = "Əlaqə Form"


class Logo(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='logos/')

    def __str__(self):
        return f'{self.name}'
    

kanatis_app/forms.py
from django import forms
from .models import *


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['name', 'email', 'subject', 'desc']
        widgets = {
            'name': forms.TextInput(attrs={
                'name': "name",
                'type': "text",
                'class': "form-control",
                # 'placeholder': "Name"
            }),
            'subject': forms.TextInput(attrs={
                'name': "surname",
                'type': "text",
                'class': "form-control",
                # 'placeholder': "Subject"
            }),
            'email': forms.TextInput(attrs={
                'name': "email",
                'type': "email",
                'class': "form-control",
                # 'placeholder': "Email"
            }),
            'desc': forms.Textarea(attrs={
                'name': "text",
                'type': "text",
                'rows': 4,
                'class': "form-control",
                # 'placeholder': "Message"
            })
        }

kanatis_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView
from .forms import ContactForm
from .models import *
from django.utils import translation


# Create your views here.
def common():
    context = {}
    context['text'] = TextPages.objects.order_by('-id').last()
    context['contact'] = Contact.objects.order_by('-id').last()
    return context


def set_language(request, lang_code):
    lang = request.META.get("HTTP_REFERER", None)
    if not lang:
        lang = "/"
    if "az" in lang:
        lang = lang.replace("az", lang_code)
    elif "en" in lang:
        lang = lang.replace("en", lang_code)

    response = redirect(lang)
    request.session[translation.LANGUAGE_SESSION_KEY] = lang_code

    return response


class HomePageView(TemplateView):
    template_name = 'index.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["carousels"] = Carousel.objects.all()[:15]
        context["services"] = Service.objects.order_by('order')[:4]
        context["posts"] = Post.objects.order_by('-id')[:3]
        context['contact'] = Contact.objects.order_by('-id').last()
        context['form'] = ContactForm()
        return context
    
    def post(self, request):
        print('-----', self.request)
        if request.method == 'POST':
            form = ContactForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('kanatis:index')


class BlogPageView(ListView):
    model = Post
    paginate_by = 6
    template_name = 'blog.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contact'] = Contact.objects.order_by('-id').last()
        context['recentposts'] = Post.objects.order_by('-id')[:8]
        return context


class BlogDetailView(DetailView):
    model = Post
    template_name = 'blog-detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contact'] = Contact.objects.order_by('-id').last()
        return context


class ServicePageView(ListView):
    model = Service
    template_name = 'services.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["services"] = Service.objects.order_by('order')[:100]
        context['contact'] = Contact.objects.order_by('-id').last()
        return context


class SubServicePageView(TemplateView):
    template_name = 'services-type.html'
    model = SubService

    def get_context_data(self, **kwargs):
        context = super(SubServicePageView, self).get_context_data(**kwargs)
        service = kwargs.get('service')
        if service:
            context['servicetypes'] = SubService.objects.filter(service__slug=service).order_by('order')
        context['contact'] = Contact.objects.order_by('-id').last()
        return context


class SubServiceDetailView(TemplateView):
    template_name = 'services-type-detail.html'
    model = SubService

    def get_context_data(self, **kwargs):
        context = super(SubServiceDetailView, self).get_context_data(**kwargs)
        subservice = kwargs.get('subservice')
        service = kwargs.get('service')
        if subservice:
            context['subservice'] = SubService.objects.order_by('order').filter(slug=subservice).first()
        if service:
            context['subservices'] = SubService.objects.order_by('order').filter(service__slug=service)
        context['contact'] = Contact.objects.order_by('-id').last()
        return context


class SubAboutDetailView(TemplateView):
    template_name = 'subabout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subabout'] = SubAboutUs.objects.filter(slug = context['slug']).first()
        context['contact'] = Contact.objects.order_by('-id').last()
        return context


def aboutus(request):
    context = common()
    return render(request, 'about-us.html', context)


def teams(request):
    context = common()
    context['member'] = Team.objects.all().order_by('order')
    return render(request, 'team.html', context)


def detail_team(request, slug):
    context = common()
    team = Team.objects.filter(slug=slug).order_by('-id').last()
    context['team'] = team
    context['services'] = TeamServices.objects.filter(service=team).order_by('id')
    context['sertificate'] = SertificateTeam.objects.filter(sertificate=team).order_by('-id')
    return render(request, 'team-single-page.html', context)


def contactus(request):
    context = common()
    form = ContactForm()
    context['form'] = form
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('kanatis:contact')

    return render(request, 'contact.html', context)

kanatis_app/templates/about-us.html
{% extends 'base.html' %}
{% block body %}
    {% load i18n %}
		<!-- PAGE CONTENT -->
		<div class="page-holder custom-page-template page-full fullscreen-page clearfix">
            <!-- SECTION 1-->
            <section class="section-holder">
                <div class="about_title">
                    <h2>{% trans 'About' %}</h2>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-7">
                            <h2 class="section-heading-title margin-b16">{{ about.title }}</h2>
                            {{ about.description|safe }}
                        </div>
                    </div>
                    <!-- /row -->
                </div>
                <!-- /container -->	
            </section>
            <!-- /SECTION 1-->	
        </div>
        <!-- /PAGE CONTENT -->

{% endblock %}

kanatis_app/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    {% load i18n %}
    {% load thumbnail %}
    {% load widget_tweaks %}

    <!-- HOME SLIDER -->
    <div class="slider-container">
        <div class="owl-carousel owl-theme home-slider">

            {% for carousel in carousels %}
                <div class="slider-post slider-item-box">
                    {% thumbnail carousel.image "1200x600" crop="center" as img %}

                        <img src="{{ img.url }}" class="img-fluid" alt="">

                    {% endthumbnail %}
{#                    <img class="img-fluid" src="{{ carousel.image.url }}" alt="">#}
                    <div class="slider-caption">
                        <div class="slider-text">
                            <h2>{{ carousel.content }}</h2>
                            <a class="btn-white"
                               href="{% url 'kanatis:services-type' carousel.service.slug %}">{% trans 'Ətraflı' %}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
    <!-- /HOME SLIDER -->
    <!-- PAGE CONTENT -->
    <div class="page-holder custom-page-template page-full fullscreen-page home-page-content clearfix">
        <!-- SECTION 1-->
        <section class="section-holder">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 offset-lg-2">
                        <div class="intro-msg margin-b108"style='margin-bottom:0'>
                            <h2 class="section-heading-title" style='margin-bottom:10px'>{{ about.title }}</h2>
                        </div>
                    </div>
                </div>
                <!-- /row -->
                <div class="row">
                    <div class="col-lg-12 margin-bm32">
                        <p>{{ about.description|truncatechars:580|safe }}
                        </p>
                    </div>
                </div>
                <div class="view-more alignc margin-t72"><a href="{% url 'kanatis:about' %}">Ətraflı</a></div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </section>
        <!-- /SECTION 1-->
        <!-- SECTION 3-->
        <section class="section-holder">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 offset-lg-2 alignc">
                        <h2 class="section-heading-title">{% trans 'Xidmətlər' %}</h2>
                    </div>
                </div>

                <div class="row practice-items-holder-v2">
                    {% for service in services %}
                        <div class="col-lg-3 col-md-6">
                            <div class="practice-item-v2">
                                {% thumbnail service.image "600x400" crop="center" as img %}
                                    <a href="{% url 'kanatis:services-type' service.slug %}">
                                        <div class="post-image"><img src="{{ img.url }}"
                                                                     class="img-fluid"
                                                                     alt=""></div>
                                    </a>
                                {% endthumbnail %}
                                {#                                <a href="{% url 'kanatis:services-type' service.slug %}">#}
                                {#                                    <div class="post-image"><img src="{{ service.image.url }}" class="img-fluid" alt="">#}
                                {#                                    </div>#}
                                {% comment %}
										600px 400px
									{% endcomment %}

                                <h5 class="practice-title-v2"><a
                                        href="{% url 'kanatis:services-type' service.slug %}">{{ service.name }}</a>
                                </h5>
                                <div class="practice-excerpt">
                                    {{ service.description }}
                                </div>
                                <a class="read-more"
                                   href="{% url 'kanatis:services-type' service.slug %}">{% trans 'Ətraflı' %}</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!-- /row -->
                <!-- /row -->
                <div class="view-more alignc margin-t72"><a
                        href="{% url 'kanatis:services' %}">{% trans 'Ətraflı' %}</a></div>
            </div>
            <!-- /container -->
        </section>


        <!-- SECTION 7-->
        <section class="section-holder">
            <div class="news_title">
                <h2>{% trans 'Xəbərlər' %}</h2>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 posts-holder post-sidebar ">
                        <div class="row">
                            {% for post in posts %}
                                <div class="col-md-6 col-lg-4">
                                    <article class=" blog-item-2col-grid">
                                        {% thumbnail post.image "1200x600" crop="center" as img %}
                                            <a href="{% url 'kanatis:blog_detail' post.slug %}">
                                                <div class="post-image"><img src="{{ img.url }}"
                                                                             class="img-fluid"
                                                                             alt=""></div>
                                            </a>
                                        {% endthumbnail %}
                                        {#                                        <a href="{% url 'kanatis:blog_detail' post.slug %}">#}
                                        {#                                            <div class="post-image"><img src="{{ post.image.url }}" class="img-fluid"#}
                                        {#                                                                         alt=""></div>#}
                                        {% comment %}
												1200px 600px
											{% endcomment %}
                                        </a>
                                        <div class="post-holder">
                                            <ul class="blog-date">
                                                <li class="meta-date">{{ post.updated_at }}</li>
                                            </ul>
                                            <h2 class="blog-title"><a
                                                    href="{% url 'kanatis:blog_detail' post.slug %}">{{ post.title }}</a>
                                            </h2>
                                            <div class="article-excerpt">{{ post.short_content|truncatechars:120 }}</div>
                                        </div>
                                    </article>
                                </div>
                            {% endfor %}

                        </div>
                        <!-- /row -->
                    </div>
                    <!-- /col-lg-12 -->
                </div>
                <div class="view-more alignc margin-b2"><a href="{% url 'kanatis:blog' %}">{% trans 'Ətraflı' %}</a>
                </div>
                <!-- /row -->
            </div>
        </section>
        <!-- /SECTION 7-->
        <!-- SECTION 9-->
        <section class="section-holder">
            <div class="contact_title">
                <h2>{% trans 'Əlaqə' %}</h2>
            </div>

            <div class="container">
                <div class="row">
                    <div class="col-lg-6 margin-bm54">
                        <span class="heading-subtitle">{% trans 'Əlaqə' %}</span>
                        <div class="icon-box-wrapper">
                            <div class="icon-box-icon"><i class="fas fa-map-marker-alt"></i></div>
                            <div class="icon-box-content">
                                <div class="icon-box-title">{% trans 'OFFICE'|upper %}</div>
                                <p class="icon-box-description">{{ contact.address }}</p>
                            </div>
                        </div>
                        <!-- /icon-box-wrapper -->
                        <div class="icon-box-wrapper">
                            <div class="icon-box-icon"><i class="fas fa-phone-alt"></i></div>
                            <div class="icon-box-content">
                                <div class="icon-box-title">{% trans 'PHONE'|upper %}</div>
                                <p class="icon-box-description">{{ contact.number }}<br/>{{ contact.office_phone }}</p>
                            </div>
                        </div>
                        <!-- /icon-box-wrapper -->
                        <div class="icon-box-wrapper">
                            <div class="icon-box-icon"><i class="far fa-envelope"></i></div>
                            <div class="icon-box-content">
                                <div class="icon-box-title">{% trans 'EMAIL'|upper %}</div>
                                <p class="icon-box-description">{{ contact.email }}</p>
                            </div>
                        </div>
                        <!-- /icon-box-wrapper -->
                        <div class="gmaps margin-t54">
                            {{ contact.gmap_embed_address|safe }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div id="contact-form-holder">
                            <form method="post" id="contact-form">
                                {% csrf_token %}

                                <div class="margin-b32"><label>{% trans 'Name'|upper %}</label>
                                    {% render_field form.name class="comm-field" %}
                                </div>
                                <div class="margin-b32"><label>{% trans 'EMAIL'|upper %}</label>
                                    {% render_field form.email class="comm-field" %}
                                </div>
                                <div class="margin-b32"><label>{% trans 'Subject'|upper %}</label>
                                    {% render_field form.subject class="comm-field" %}
                                </div>
                                <div class="margin-b32"><label>{% trans 'Message'|upper %}</label>
                                    {% render_field form.desc class="comm-field" id='msg-contact' rows='5' %}</div>
                                <p class="antispam">Leave this empty: <input type="text" name="url"/></p>
                                <p><input type="submit" value="{% trans 'Send message'|upper %}" id="submit"/></p>
                            </form>

                        </div>
                        <!-- contact-form-holder-->
                        <div id="output-contact"></div>
                    </div>
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </section>
        <!-- /SECTION 9-->

    </div>
    <!-- /PAGE CONTENT -->

{% endblock body %}

kanatis_app/templates/services-type-detail.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    {% load i18n %}
    {% load thumbnail %}


    <div class="service_title">
        <h2>{{ subservice.title }}</h2>
    </div>
    <!-- PAGE CONTENT -->
    <div class="page-holder custom-page-template page-full fullscreen-page clearfix">
        <!-- SECTION 1-->
        <section class="section-holder">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        <img src="{{ subservice.image.url }}" class="img-fluid margin-b16" alt=""/>
                        {{ subservice.content|safe }}
                    </div>
                    <!-- /col-lg-9 -->
                    <div class="col-lg-3">
                        <aside>
                            <ul>
                                <li class="widget">
                                    <h5 class="widgettitle">{% trans 'Xidmətlər' %}</h5>
                                    <div class="sidebar widget_recent_entries">
                                        <ul>
                                            {% for subservice in subservices %}
                                                <li>
                                                    <a href="{% url 'kanatis:service-detail' subservice.service.slug subservice.slug %}">{{ subservice.title }}</a>
                                                </li>
                                            {% endfor %}

                                        </ul>
                                    </div>
                                </li>
                            </ul>
                        </aside>
                    </div>
                    <!-- /col-lg-3 -->
                </div>
                <!-- /row -->
            </div>
            <!-- /container -->
        </section>
        <!-- /SECTION 1-->
    </div><!-- /PAGE CONTENT -->

{% endblock body %}
	

kanatis_app/templates/subabout.html
{% extends 'base.html' %}
{% block body %}
    {% load i18n %}
		<!-- PAGE CONTENT -->
		<div class="page-holder custom-page-template page-full fullscreen-page clearfix">
            <!-- SECTION 1-->
            <section class="section-holder">
                <div class="about_title">
                    <h2>{% trans 'About' %}</h2>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-7">
                            <h2 class="section-heading-title margin-b16">{{ subabout.title }}</h2>
                            {{ subabout.description|safe }}
                        </div>
                    </div>
                    <!-- /row -->
                </div>
                <!-- /container -->	
            </section>
            <!-- /SECTION 1-->	
        </div>
        <!-- /PAGE CONTENT -->

{% endblock %}